####### llm-data #######
[boss.llm-data]
endpoint    = "http://shjd-inner-boss.bilibili.co"
access_key  = "XsoNq0QPQJToqHsG"
secret_key  = "ylQHuuY8LIkIbjSHqsoW0tUD9aehQQse"
bucket      = "llm-data"
object_path = ""

[boss.llm-data.config]
signature_version = "s3v4"
connect_timeout   = 20
read_timeout      = 20

[boss.llm-data.config.s3]
addressing_style = "path"
max_concurrent_requests = 10
max_bandwidth = "50MB/s"

[boss.llm-data.config.retries]
max_attempts = 5

[boss.llm-data.transfer_config]
max_concurrency=10
multipart_chunksize=33554432
multipart_threshold=134217728
num_download_attempts=10
max_io_queue=256
io_chunksize=4194304


####### llm_snapshot #######
[boss.llm_snapshot]
endpoint    = "http://jssz-inner-boss.bilibili.co"
access_key  = "T90UlXgHTqGfovOh"
secret_key  = "tPIA6vHV7Jxkpmr4Ria75pj773AqDAZI"
bucket      = "llm_snapshot"
object_path = ""

[boss.llm_snapshot.config]
signature_version = "s3v4"
connect_timeout   = 5
read_timeout      = 5

[boss.llm_snapshot.config.s3]
addressing_style = "path"
max_concurrent_requests = 20

[boss.llm_snapshot.config.retries]
max_attempts = 5

[boss.llm_snapshot.transfer_config]
max_concurrency=10
multipart_chunksize=67108864
multipart_threshold=134217728
num_download_attempts=10
max_io_queue=256
io_chunksize=8388608


####### llm_models_70b #######
[boss.llm_models_70b]
endpoint    = "http://jssz-inner-boss.bilibili.co"
access_key  = "kwwtoKJ6RwZCKQ3s"
secret_key  = "eAUh08q2UmekXvzYuUs7u3TOLmrTBEtf"
bucket      = "llm_models_70b"
object_path = ""

[boss.llm_models_70b.config]
signature_version = "s3v4"
connect_timeout   = 1
read_timeout      = 1

[boss.llm_models_70b.config.s3]
addressing_style = "path"
max_concurrent_requests = 10
multipart_chunksize = 20

[boss.llm_models_70b.config.retries]
max_attempts = 5


####### ai_models #######
[boss.ai_models]
endpoint    = "http://jssz-inner-boss.bilibili.co"
access_key  = "d92cc9a495da7edc"
secret_key  = "107108c8e45e09fa6521b99f04fb4100"
bucket      = "ai_models"
object_path = ""

[boss.ai_models.config]
signature_version = "s3v4"
connect_timeout   = 1
read_timeout      = 1

[boss.ai_models.config.s3]
addressing_style = "path"
max_concurrent_requests = 10
multipart_chunksize = 20

[boss.ai_models.config.retries]
max_attempts = 5
